"""initial schema

Builds the full AERP schema from the ORM metadata. This is the single source of
truth for the baseline; every subsequent change is a normal autogenerated Alembic
migration that diffs against this state.

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-24
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op

from app.models import Base

# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Create every table declared on the ORM metadata, in dependency order.
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
